# Generated by Django 3.1.2 on 2021-02-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_desc',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=2000),
        ),
    ]
